---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 10m
  url: https://prometheus-community.github.io/helm-charts
  timeout: 3m

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kube-state-metrics
  namespace: flux-system
spec:
  interval: 10m
  url: https://kubernetes.github.io/kube-state-metrics
  timeout: 3m

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus
      version: 14.1.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 5m
  values:
    server:
      persistentVolume:
        storageClass: "nfs-dynamic"
    alertmanager:
      persistentVolume:
        storageClass: "nfs-dynamic"

