apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: ingress-nginx
spec:
  selector:
    app: grafana
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
